### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ppplin** [IndustryEssentials/label-free#19]
数据库可以改为配置的么

**Comment by yance-dev** [comment]
> 数据库可以改为配置的么

可以的，将docker-compose中的两处环境变量 `SQLALCHEMY_DATABASE_URI` 指定为自己的数据库就可以

具体的格式为：
```
mysql+pymysql://username:password@host:port/labelfree
```
可以根据自己的需要，填好数据库信息


修改完成以后web和worker就可以连接外部的mysql
