### ISSUE TITLE
label-free 自动保存功能

### ISSUE THREAD

**Issue by yance-dev** [IndustryEssentials/label-free#4]
label-free 如果有标注完自动保存功能会不会更方便一些，现在好像每张图标注完都要手动submit，才能跳到下一张

_Originally posted by @ChinaRush in https://github.com/IndustryEssentials/label-free/issues/3#issuecomment-1154636186_

**Comment by yance-dev** [comment]
@ChinaRush 这边目前是有保存快捷键的，`S`即可保存并自动跳转到下一个待标注图片，使用快捷键的话应该会减少手动submit的操作

**Comment by ChinaRush** [comment]
是的。我的意思是能否自动保存每次的标注事件，然后最后只需submit一次，即可跳转到ymir web界面。

**Comment by yance-dev** [comment]
> 是的。我的意思是能否自动保存每次的标注事件，然后最后只需submit一次，即可跳转到ymir web界面。

嗯嗯，我们会评估这个需求，并持续跟进哈
