### ISSUE TITLE
LabelFree平台对整个数据包图片尺寸的要求统一吗？

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [IndustryEssentials/label-free#5]
标注完数据下载之后发现图片尺寸和标签xml内的尺寸内容不符合
<img width="545" alt="image" src="https://user-images.githubusercontent.com/88470384/174592917-eae50dca-5bac-4a7d-ad0d-87b532ef3def.png">

**Comment by yance-dev** [comment]
我们会尽快修复这个问题

**Comment by yance-dev** [comment]
你好，我们最近已经修复了这个问题，麻烦您拉取最新的label free docker镜像，进行更新：

```shell
docker pull  labelfree/open:latest

docker-compose -f docker-compose.labelfree.yml up -d
```
